2021-08-09 13:03:33,071 INFO    MainThread:1001948 [wandb_setup.py:_flush():69] setting env: {'entity': 'katiez', 'project': 'cgan_earth', 'api_key': 'be4ee90fd1224a904f7f4764a16a13960cafe300'}
2021-08-09 13:03:33,072 INFO    MainThread:1001948 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-09 13:03:33,072 INFO    MainThread:1001948 [wandb_init.py:_log_setup():337] Logging user logs to /rds/general/user/jz12018/home/cgan_earth/wandb/run-20210809_130332-8xeva61l/logs/debug.log
2021-08-09 13:03:33,073 INFO    MainThread:1001948 [wandb_init.py:_log_setup():338] Logging internal logs to /rds/general/user/jz12018/home/cgan_earth/wandb/run-20210809_130332-8xeva61l/logs/debug-internal.log
2021-08-09 13:03:33,073 INFO    MainThread:1001948 [wandb_init.py:init():370] calling init triggers
2021-08-09 13:03:33,074 INFO    MainThread:1001948 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-08-09 13:03:33,074 INFO    MainThread:1001948 [wandb_init.py:init():419] starting backend
2021-08-09 13:03:33,074 INFO    MainThread:1001948 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-09 13:03:33,138 INFO    MainThread:1001948 [backend.py:ensure_launched():135] starting backend process...
2021-08-09 13:03:33,179 INFO    MainThread:1001948 [backend.py:ensure_launched():140] started backend process with pid: 1002317
2021-08-09 13:03:33,181 INFO    MainThread:1001948 [wandb_init.py:init():424] backend started and connected
2021-08-09 13:03:33,183 INFO    MainThread:1001948 [wandb_init.py:init():472] updated telemetry
2021-08-09 13:03:33,184 INFO    MainThread:1001948 [wandb_init.py:init():491] communicating current version
2021-08-09 13:03:34,546 INFO    MainThread:1001948 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.11.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-08-09 13:03:34,547 INFO    MainThread:1001948 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-08-09 13:03:34,755 INFO    MainThread:1001948 [wandb_init.py:init():529] starting run threads in backend
2021-08-09 13:03:34,832 INFO    MainThread:1001948 [wandb_run.py:_console_start():1623] atexit reg
2021-08-09 13:03:34,834 INFO    MainThread:1001948 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.REDIRECT
2021-08-09 13:03:34,838 INFO    MainThread:1001948 [wandb_run.py:_redirect():1502] Redirecting console.
2021-08-09 13:03:34,842 INFO    MainThread:1001948 [wandb_run.py:_redirect():1558] Redirects installed.
2021-08-09 13:03:34,842 INFO    MainThread:1001948 [wandb_init.py:init():554] run started, returning control to user process
2021-08-09 13:03:34,845 INFO    MainThread:1001948 [wandb_config.py:__setitem__():141] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x14d883c98470>>
2021-08-09 13:03:34,845 INFO    MainThread:1001948 [wandb_run.py:_config_callback():872] config_cb no_cuda False None
2021-08-09 13:03:34,847 INFO    MainThread:1001948 [wandb_config.py:__setitem__():141] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x14d883c98470>>
2021-08-09 13:03:34,847 INFO    MainThread:1001948 [wandb_run.py:_config_callback():872] config_cb seed 42 None
2021-08-09 13:03:34,848 INFO    MainThread:1001948 [wandb_config.py:__setitem__():141] config set log_interval = 100 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x14d883c98470>>
2021-08-09 13:03:34,848 INFO    MainThread:1001948 [wandb_run.py:_config_callback():872] config_cb log_interval 100 None
2021-08-09 13:03:34,849 INFO    MainThread:1001948 [wandb_watch.py:watch():40] Watching
2021-08-09 13:03:34,851 INFO    MainThread:1001948 [wandb_watch.py:watch():40] Watching
2021-08-09 13:03:34,959 INFO    MainThread:1001948 [wandb_run.py:_atexit_cleanup():1593] got exitcode: 1
2021-08-09 13:03:34,962 INFO    MainThread:1001948 [wandb_run.py:_restore():1565] restore
2021-08-09 13:03:37,356 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 742
}

2021-08-09 13:03:37,624 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 742
}

2021-08-09 13:03:37,787 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 3489
}

2021-08-09 13:03:37,891 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 3489
}

2021-08-09 13:03:37,994 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 742
  total_bytes: 3489
}

2021-08-09 13:03:38,098 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3489
  total_bytes: 3489
}

2021-08-09 13:03:38,202 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3489
  total_bytes: 3489
}

2021-08-09 13:03:38,305 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3489
  total_bytes: 3489
}

2021-08-09 13:03:38,408 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3489
  total_bytes: 3489
}

2021-08-09 13:03:38,512 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3489
  total_bytes: 3489
}

2021-08-09 13:03:38,800 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3489
  total_bytes: 3489
}

2021-08-09 13:03:38,904 INFO    MainThread:1001948 [wandb_run.py:_wait_for_finish():1715] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3489
  total_bytes: 3489
}

2021-08-09 13:03:40,102 INFO    MainThread:1001948 [wandb_run.py:_show_files():1937] logging synced files
