Starting Training Loop...
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
Traceback (most recent call last):
  File "run_cgan_earth.py", line 38, in <module>
    batch_size, lr, device, wandb_name)
  File "/rds/general/user/jz12018/home/cgan_earth/code_files/model.py", line 49, in train
    disc_real = netD(real_data, D_labels).mean()
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/rds/general/user/jz12018/home/cgan_earth/code_files/networks.py", line 102, in forward
    crit_pred = self.crit(x)
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 4, 4], expected input[20, 8, 128, 128] to have 3 channels, but got 8 channels instead