Starting Training Loop...
data shape: (20, 3, 128, 128)
label shape: [1. 3. 4. 4. 4. 0. 2. 3. 0. 3. 1. 2. 2. 4. 2. 0. 0. 1. 3. 1.]
torch.Size([20, 3, 128, 128])
Traceback (most recent call last):
  File "run_cgan_earth.py", line 38, in <module>
    batch_size, lr, device, wandb_name)
  File "/rds/general/user/jz12018/home/cgan_earth/code_files/model.py", line 46, in train
    disc_real = netD(real_data, D_labels).mean()
  File "/rds/general/user/jz12018/home/venv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/rds/general/user/jz12018/home/cgan_earth/code_files/networks.py", line 101, in forward
    torch.cat([image, labels], 1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument tensors in method wrapper__cat)